version: "3.1"
services:
  mysql-dev:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "accountadministration_system"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - aas-mysql-dev:/var/lib/mysql
  aas-dev:
    image: accountadministrationsystem:latest
    depends_on:
      - mysql-dev
    ports:
      - "8100:8080"
      - "8282:8181"
      - "4848:4848"
volumes:
  aas-mysql-dev: